agoravai/force-app/main/default/objects/Candidato__c/Candidato__c.object-meta.xml
<CustomObject>
    <description>Um candidato é uma pessoa que foi convidada para participar dos jogos mas ainda não aceitou.</description>
    <label>Candidato</label>
    <nameField>
        <label>Nome do Candidato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

agoravai/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>J-{000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

agoravai/force-app/main/default/objects/Jogador__c/fields/Candidato__c.field-meta.xml
<CustomField>
    <fullName>Candidato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>referente o registro do candidato</description>
    <inlineHelpText>referente o registro do candidato</inlineHelpText>
    <label>Candidato</label>
    <referenceTo>Candidato__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores</relationshipName>
    <type>Lookup</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Selecione o campo quando o jogador for eliminado da brincadeira</description>
    <inlineHelpText>Jogador eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/Nick__c.field-meta.xml
<CustomField>
    <fullName>Nick__c</fullName>
    <description>O apelido do jogador</description>
    <label>Nick</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <description>Usado para informar o jogo que o jogador está vinculado</description>
    <inlineHelpText>Usado para informar o jogo que o jogador está vinculado</inlineHelpText>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/ValorPagar__c.field-meta.xml
<CustomField>
    <fullName>ValorPagar__c</fullName>
    <label>Valor a Pagar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

agoravai/force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <description>Usado para representar o jogo da série &quot;Round 6&quot;</description>
    <label>Round</label>
    <nameField>
        <displayFormat>Round-{00000}</displayFormat>
        <label>Número do Round</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

agoravai/force-app/main/default/objects/Round__c/fields/PremioTotal__c.field-meta.xml
<CustomField>
    <fullName>PremioTotal__c</fullName>
    <label>Premio total</label>
    <summarizedField>Jogador__c.Divida__c</summarizedField>
    <summaryForeignKey>Jogador__c.Round__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

agoravai/force-app/main/default/objects/Round__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status do round</description>
    <inlineHelpText>Status do round</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em definição</fullName>
                <default>true</default>
                <label>Em definição</label>
            </value>
            <value>
                <fullName>Coletando candidatos</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

agoravai/force-app/main/default/objects/Round__c/fields/TotalJogadoresEliminados__c.field-meta.xml
<CustomField>
    <fullName>TotalJogadoresEliminados__c</fullName>
    <description>Valor total de jogadores eliminados neste jogo</description>
    <inlineHelpText>Valor total de jogadores eliminados neste jogo</inlineHelpText>
    <label>Total de Jogadores Eliminados</label>
    <summaryFilterItems>
        <field>Jogador__c.Eliminado__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Jogador__c.Round__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

agoravai/force-app/main/default/objects/Round__c/fields/Vencedor__c.field-meta.xml
<CustomField>
    <fullName>Vencedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Jogador vencedor do torneio</description>
    <inlineHelpText>Jogador vencedor do torneio</inlineHelpText>
    <label>Vencedor</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipLabel>Rounds</relationshipLabel>
    <relationshipName>Rounds</relationshipName>
    <type>Lookup</type>
</CustomField>

agoravai/force-app/main/default/classes/RoundsSelector.cls
public without sharing class RoundsSelector {

    public static List<Round__c> selectByRoundsIdsWithJogadores(Set<Id> ids) {
        return [
            SELECT  Id, TotalJogadoresEliminados__c, PremioTotal__c,
                    (
                        SELECT Id, ValorPagar__c, RecordTypeId, RecordType.DeveloperName, Candidato__r.Email__c
                        FROM Jogadores__r 
                        WHERE Eliminado__c = true
                    )
            FROM Round__c 
            WHERE Id IN :ids
        ];
    }

    public static List<Round__c> selectRoundsByIdStatusJogadoresVivos(Set<Id> roundsIds, Set<String> statusList) {
        return [
            SELECT 
                Id,
                Vencedor__c,
                (SELECT Id FROM Jogadores__r WHERE Eliminado__c = false)
            FROM Round__c
            WHERE 
                    Id = :roundsIds          
                AND Status__c IN :statusList
        ];
    }

    public static List<Round__c> selectAllRoundsWithJogadores() {
        return [
            SELECT  Id, Name, TotalJogadoresEliminados__c, PremioTotal__c,
                    (
                        SELECT Id, Nick__c, Candidato__r.Name
                        FROM Jogadores__r 
                        WHERE Eliminado__c = true
                    )
            FROM Round__c
        ];
    }

    public static List<Round__c> selectAllRoundsWithJogadoresNaoEliminados() {
        return [
            SELECT Id, Name, Vencedor__c, PremioTotal__c, (SELECT Id, Name,  Candidato__r.Name FROM Jogadores__r)
            FROM Round__c
            WHERE Status__c = 'Em Andamento'
        ];
    }

}