agoravai/force-app/main/default/objects/Assassinato__c/Assassinato__c.object-meta.xml
<CustomObject>
    <label>Assassinato</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Número do Assassinato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assassinatos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

agoravai/force-app/main/default/objects/Assassinato__c/fields/Assassinado__c.field-meta.xml
<CustomField>
    <fullName>Assassinado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assassinado</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipLabel>Assassinatos (Assassinado)</relationshipLabel>
    <relationshipName>Assassinados</relationshipName>
    <type>Lookup</type>
</CustomField>

agoravai/force-app/main/default/objects/Assassinato__c/fields/DataHora__c.field-meta.xml
<CustomField>
    <fullName>DataHora__c</fullName>
    <label>Data e Hora</label>
    <type>DateTime</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>J-{000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

agoravai/force-app/main/default/objects/Jogador__c/fields/DataMorte__c.field-meta.xml
<CustomField>
    <fullName>DataMorte__c</fullName>
    <description>Usado para informar a data e hora da eliminação do jogador</description>
    <inlineHelpText>Data e hora da eliminação do jogador</inlineHelpText>
    <label>Data da Morte</label>
    <type>DateTime</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Selecione o campo quando o jogador for eliminado da brincadeira</description>
    <inlineHelpText>Jogador eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/Morreu__c.field-meta.xml
<CustomField>
    <fullName>Morreu__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Morreu</label>
    <type>Checkbox</type>
</CustomField>

agoravai/force-app/main/default/classes/AssassinatosTriggerHandler.cls
public without sharing class AssassinatosTriggerHandler {

    public static void afterInsert(List<Assassinato__c> records) {
        List<Jogador__c> jogadoresMortos = new List<Jogador__c>();
        for (Assassinato__c record : records) {
            mataJogadorAssassinado(record, jogadoresMortos);
        }
        update jogadoresMortos;
    }

    static void mataJogadorAssassinado(Assassinato__c record, List<Jogador__c> jogadoresMortos) {
        jogadoresMortos.add(
            new Jogador__c(
                Id = record.Assassinado__c,
                Eliminado__c = true,
                Morreu__c = true,
                DataMorte__c = record.DataHora__c
            )
        );
    }
}