agoravai/force-app/main/default/objects/Assassinato__c/Assassinato__c.object-meta.xml
<CustomObject>
    <label>Assassinato</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Número do Assassinato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assassinatos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

agoravai/force-app/main/default/objects/Assassinato__c/fields/Assassinado__c.field-meta.xml
<CustomField>
    <fullName>Assassinado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assassinado</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipLabel>Assassinatos (Assassinado)</relationshipLabel>
    <relationshipName>Assassinados</relationshipName>
    <type>Lookup</type>
</CustomField>

agoravai/force-app/main/default/objects/Assassinato__c/fields/Assassino__c.field-meta.xml
<CustomField>
    <fullName>Assassino__c</fullName>
    <label>Assassino(a)</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipLabel>Assassinatos</relationshipLabel>
    <relationshipName>Assassinos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

agoravai/force-app/main/default/objects/Assassinato__c/fields/DataHora__c.field-meta.xml
<CustomField>
    <fullName>DataHora__c</fullName>
    <label>Data e Hora</label>
    <type>DateTime</type>
</CustomField>

agoravai/force-app/main/default/classes/AssassinatosTriggerHandlerTest.cls
@isTest
public with sharing class AssassinatosTriggerHandlerTest {
    @isTest
    static void afterInsertTest() {
        //prepara o teste
        List<Assassinato__c> records = new List<Assassinato__c>();
        records.add(
            new Assassinato__c(
                Assassinado__c = 'a015f000009o0lfAAA',
                Assassino__c = 'a015f00000Cnhc0AAB',
                DataHora__c = System.now()
            )
        );
        //executa o teste
        Test.startTest();
        AssassinatosTriggerHandler.afterInsert(records);
        Test.stopTest();
        //relatorio do teste
    }
    
}