agoravai/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>J-{000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

agoravai/force-app/main/default/objects/Jogador__c/fields/DataMorte__c.field-meta.xml
<CustomField>
    <fullName>DataMorte__c</fullName>
    <description>Usado para informar a data e hora da eliminação do jogador</description>
    <inlineHelpText>Data e hora da eliminação do jogador</inlineHelpText>
    <label>Data da Morte</label>
    <type>DateTime</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Selecione o campo quando o jogador for eliminado da brincadeira</description>
    <inlineHelpText>Jogador eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/MembroStaff__c.field-meta.xml
<CustomField>
    <fullName>MembroStaff__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Usado quando o jogador é um membro da staff</description>
    <inlineHelpText>Usado quando o jogador é um membro da staff</inlineHelpText>
    <label>Membro da Staff</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Jogadores</relationshipName>
    <type>Lookup</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/Morreu__c.field-meta.xml
<CustomField>
    <fullName>Morreu__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Morreu</label>
    <type>Checkbox</type>
</CustomField>

agoravai/force-app/main/default/classes/JogadoresTriggerHandler.cls
public without sharing class JogadoresTriggerHandler {
    public static void beforeUpdate(List<Jogador__c> records, Map<Id, Jogador__c> oldMap) {
        for (Jogador__c jogador : records) { //realiza uma iteração
            beforeUpdate(jogador, oldMap.get(jogador.Id));
        }
    }

    private static void beforeUpdate(Jogador__c record, Jogador__c recordOld) {
        handleEliminacaoMorte(record, recordOld);
    }

    private static Boolean isChanged(Jogador__c record, Jogador__c recordToCompare, Schema.SObjectField fieldToEvaluate) {
        return isChanged(record.get(fieldToEvaluate), recordToCompare.get(fieldToEvaluate));
    }

    private static Boolean isChanged(Object value, Object valueToCompare) {
        return value != valueToCompare;
    }

    private static void setValue(Jogador__c record, Schema.SObjectField field, Object value) {
        record.put(field, value);
    }

    private static void handleEliminacaoMorte(Jogador__c record, Jogador__c recordOld) {

        if (foiEliminado(record, recordOld) || morreu(record, recordOld)) {

            //se é jogador comum OU se morreu
            if (ehJogadorComum(record) || morreu(record, recordOld)) { 
                System.debug('é jogador comum OU morreu');
                setMorte(record);

            } else if (!ehJogadorComum(record)) { //É jogador staff (e foi somente eliminado)
                System.debug('é jogador staff e foi somente eliminado');
                setEliminado(record);

            } else { //não deve entrar em nenhum momento aqui
                System.debug('você não deveria estar lendo isso');
            }
        }
    }

    private static Boolean foiEliminado(Jogador__c record,Jogador__c recordOld) {
        return isChanged(record, recordOld, Jogador__c.Eliminado__c);
    }

    private static Boolean morreu(Jogador__c record, Jogador__c recordOld) {
        return isChanged(record, recordOld, Jogador__c.Morreu__c);
    }

    private static Boolean ehJogadorComum(Jogador__c record) {
        /*
        if (String.isBlank(record.MembroStaff__c)) { //é jogador comum
            return true;

        } else { //é membro da staff
            return false;
        }
        */
        return record.RecordTypeId.equals(
            Schema.SObjectType.Jogador__c.getRecordTypeInfosByDeveloperName().get(Label.RECORD_TYPE_DEVELOPER_NAME_JOGADOR_PADRAO).getRecordTypeId()
        );
    }

    private static void setMorte(Jogador__c record) {
        setEliminado(record);
        setValue(record, Jogador__c.Morreu__c, true);
        setValue(record, Jogador__c.DataMorte__c, System.now());
    }

    private static void setEliminado(Jogador__c record) {
        setValue(record, Jogador__c.Eliminado__c, true);
    }
}