agoravai/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>J-{000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

agoravai/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Selecione o campo quando o jogador for eliminado da brincadeira</description>
    <inlineHelpText>Jogador eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

agoravai/force-app/main/default/objects/ParticipantePartida__c/ParticipantePartida__c.object-meta.xml
<CustomObject>
    <description>Tabela de ligação entre Jogador e Partida</description>
    <label>Participante da Partida</label>
    <nameField>
        <displayFormat>Par-{000000}</displayFormat>
        <label>Número do Participante da Partida</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes da Partida</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

agoravai/force-app/main/default/objects/ParticipantePartida__c/fields/Jogador__c.field-meta.xml
<CustomField>
    <fullName>Jogador__c</fullName>
    <description>Jogador da Partida</description>
    <inlineHelpText>Jogador da Partida</inlineHelpText>
    <label>Jogador</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipLabel>Participantes da Partida</relationshipLabel>
    <relationshipName>ParticipantesPartida</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

agoravai/force-app/main/default/objects/ParticipantePartida__c/fields/Partida__c.field-meta.xml
<CustomField>
    <fullName>Partida__c</fullName>
    <description>Partida que o jogador participou</description>
    <inlineHelpText>Partida que o jogador participou</inlineHelpText>
    <label>Partida</label>
    <referenceTo>Partida__c</referenceTo>
    <relationshipLabel>Participantes da Partida</relationshipLabel>
    <relationshipName>ParticipantesPartida</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

agoravai/force-app/main/default/objects/Partida__c/Partida__c.object-meta.xml
<CustomObject>
    <description>Partida de cada round</description>
    <label>Partida</label>
    <nameField>
        <label>Nome de Partida</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partidas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

agoravai/force-app/main/default/objects/Partida__c/fields/TerminoPartida__c.field-meta.xml
<CustomField>
    <fullName>TerminoPartida__c</fullName>
    <description>Date e hora de término da partida</description>
    <inlineHelpText>Date e hora de término da partida</inlineHelpText>
    <label>Término da Partida</label>
    <type>DateTime</type>
</CustomField>

agoravai/force-app/main/default/classes/BatatinhaFrita.cls
public class BatatinhaFrita implements IPartida {
    public void execute(Id idPartida) {
        List<ParticipantePartida__c> participantes = [SELECT Jogador__c FROM ParticipantePartida__c WHERE Partida__c = :idPartida];
        
        List<Jogador__c> jogadores = new List<Jogador__c>();
        //mesma coisa que:
        //Jogador__c[] jogadores = new List<Jogador__c>();
        
        Integer mortes = (Integer) participantes.size() / 2;
        
        for(Integer i = 0; i < mortes; i++) {
            jogadores.add(new Jogador__c(Id = participantes[i].Jogador__c, Eliminado__c = true));
        }
        
        //System.debug(jogadores);
        update jogadores;
        
        update new Partida__c(Id = idPartida, TerminoPartida__c = System.now());
    }
}