agoravai/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>J-{000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

agoravai/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Selecione o campo quando o jogador for eliminado da brincadeira</description>
    <inlineHelpText>Jogador eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/Forca__c.field-meta.xml
<CustomField>
    <fullName>Forca__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Força</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/Inteligencia__c.field-meta.xml
<CustomField>
    <fullName>Inteligencia__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Inteligência</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/Morreu__c.field-meta.xml
<CustomField>
    <fullName>Morreu__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Morreu</label>
    <type>Checkbox</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/Nick__c.field-meta.xml
<CustomField>
    <fullName>Nick__c</fullName>
    <description>O apelido do jogador</description>
    <label>Nick</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <description>Usado para informar o jogo que o jogador está vinculado</description>
    <inlineHelpText>Usado para informar o jogo que o jogador está vinculado</inlineHelpText>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

agoravai/force-app/main/default/objects/Jogador__c/fields/Velocidade__c.field-meta.xml
<CustomField>
    <fullName>Velocidade__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Velocidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

agoravai/force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <description>Usado para representar o jogo da série &quot;Round 6&quot;</description>
    <label>Round</label>
    <nameField>
        <displayFormat>Round-{00000}</displayFormat>
        <label>Número do Round</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

agoravai/force-app/main/default/objects/Round__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status do round</description>
    <inlineHelpText>Status do round</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em definição</fullName>
                <default>true</default>
                <label>Em definição</label>
            </value>
            <value>
                <fullName>Coletando candidatos</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

agoravai/force-app/main/default/objects/Round__c/fields/Vencedor__c.field-meta.xml
<CustomField>
    <fullName>Vencedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Jogador vencedor do torneio</description>
    <inlineHelpText>Jogador vencedor do torneio</inlineHelpText>
    <label>Vencedor</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipLabel>Rounds</relationshipLabel>
    <relationshipName>Rounds</relationshipName>
    <type>Lookup</type>
</CustomField>

agoravai/force-app/main/default/classes/JogadoresSelector.cls
public without sharing class JogadoresSelector {

    public static List<Jogador__c> selectJogadoresNaoEliminadosByRoundsInSituation(Set<Id> ids, Set<String> situacao) {
        return [
            SELECT Id, Name, Nick__c, Eliminado__c, Morreu__c, Round__c, Round__r.Id, Round__r.Status__c
            FROM Jogador__c
            WHERE Round__r.Status__c IN :situacao
            AND Eliminado__c = false
            AND Id IN :ids
            ORDER BY Round__c
        ];
    }

    public static List<Jogador__c> selectJogadoresNaoEliminados() {
        return [
            SELECT Id, Name, Nick__c, Forca__c, Round__r.Status__c, Inteligencia__c, Velocidade__c
            , Eliminado__c 
            FROM Jogador__c
            WHERE Round__r.Status__c = 'Em Andamento' AND Eliminado__c = false
        ];
    }
}

/*
trigger em jogador
	verifica se sobrou somente 1 vivo
		caso positivo
			atualiza o campo vencedor__c no round
		caso negativo
			não faz nada
            */